version: '3.2'

services:
  auth-service:
    image: sabin2000/ticketblock-auth-service
    build: 
      context: ../backend/services/authentication
      dockerfile: Dockerfile

    ports:
      - "5299:5299"
    restart: always
      
    volumes:
      - /app/node_modules
      - ../backend/services/authentication:/app


  nft-service:
    image: sabin2000/ticketblock-nft-service

    build:
      context: ../backend/services/nfts
      dockerfile: Dockerfile

    volumes:
      - /app/node_modules
      - ../backend/services/nfts:/app

    restart: always
    depends_on:
      - auth-service
      
    ports:
      - "5201:5201"

  frontend:
    image: sabin2000/ticketblock-frontend-service

    build:
      context: ../frontend
      dockerfile: Dockerfile

    volumes:
      - /app/node_modules
      - ../frontend:/app

    ports:
      - "3000:3000"

    restart: always
  
  database-service:
    image: mongo

    ports:
      - "27017:27017"

    restart: always

    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db

volumes:
  mongodb_data_volume: